name: Check apns update

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: "SM-G998B"
            region: "DBT"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y lz4 python3-pip simg2img
       pip3 install git+https://github.com/Linux4/samloader.git

    - name: Compare latest version with current version
      id: check
      run: |
       need_update=0
       latest=`samloader -m ${{ matrix.model }} -r ${{ matrix.region }} checkupdate`
       latest_short=`echo $latest | cut -f1 -d '/'`
       current=`cat current.${{ matrix.model }}` || need_update=1
       [[ $latest != $current ]] && need_update=1
       echo "latest_version=$latest" >> $GITHUB_OUTPUT
       echo "latest_version_short=$latest_short" >> $GITHUB_OUTPUT
       echo "need_update=$need_update" >> $GITHUB_OUTPUT

    - name: Fetch firmware
      if: steps.check.outputs.need_update == 1
      run: |
       samloader -m ${{ matrix.model }} -r ${{ matrix.region }} download -v ${{ steps.check.outputs.latest_version }} -o ${{ matrix.model }}-${{ steps.check.outputs.latest_version_short }}.zip.enc4 -D
       mkdir -p out
       echo ${{ steps.check.outputs.latest_version_short }} >> version.txt

    - name: Extract apns-conf.xml
      if: steps.check.outputs.need_update == 1
      run: |
       unzip -p ${{ matrix.model }}-${{ steps.check.outputs.latest_version_short }}.zip "AP*" | tar xvf - super.img.lz4
       rm ${{ matrix.model }}-${{ steps.check.outputs.latest_version_short }}.zip
       lz4 -d -m --rm super.img.lz4
       simg2img super.img super.raw
       wget https://raw.githubusercontent.com/unix3dgforce/lpunpack/master/lpunpack.py
       python3 lpunpack.py -p system super.raw .
       rm lpunpack.py super.img super.raw
       mkdir root
       sudo mount -o ro ./system.img ./root
       cp root/system/etc/apns-conf.xml .
       sudo umount ./root
       rm system.img

    - name: Commit changes
      if: steps.check.outputs.need_update == 1
      run: |
       git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
       git config --local user.name "github-actions[bot]"
       git pull origin ${{github.ref}} --ff-only
       echo ${{ steps.check.outputs.latest_version }} > current.${{ matrix.model }}
       git add current.${{ matrix.model }}
       git add apns-conf.xml
       git commit -m "${{ matrix.model }}: ${{ steps.check.outputs.latest_version }}"
       git tag ${{ steps.check.outputs.latest_shortversion }}

    - name: Push changes to repo
      if: steps.check.outputs.need_update == 1
      uses: ad-m/github-push-action@master
      with:
        tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
